CREATE TABLE b_awz_europost_pvz (
    ID int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PVZ_ID varchar(255) NOT NULL,
    TOWN varchar(65) NOT NULL,
    PRM text,
    PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX b_awz_europost_pvz_pvz_id ON b_awz_europost_pvz (pvz_id);
CREATE INDEX b_awz_europost_pvz_town ON b_awz_europost_pvz (town);